name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks-on-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Build the container
        run: sudo docker build -t checker .

      - name: Run `pkgcheck scan`
        run: sudo docker run -t checker pkgcheck scan --repo toku-sa-n --exit info

        # Run `emerge` with the ebuilds that have been changed
        # First `grep` filters the ebuilds that have been added, copied, modified, or renamed
        # Second `sed` extracts the category and package name (e.g. `dev-ml/coq-lsp/coq-lsp-0.1.0.ebuild` -> `dev-ml/coq-lsp-0.1.0`)
      - name: Emerge
        run: git diff main --name-only --diff-filter=ACMR \
          | grep '^[^/]\+/[^/]\+/.+ebuild$'
          | sed -r 's/^(.[^/]+)\/.[^/]+\/(.[^/]+)\/.ebuild$/=\1\/\2/g'
          | xargs -n1 sudo docker run -t checker emerge --oneshot --verbose --tree --quiet

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Run `prettier`
        run: npx --yes prettier --check .
