name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks-on-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Build the container
        run: sudo docker build -t checker .

      - name: Run `pkgcheck`
        run: sudo docker run checker pkgcheck scan --repo toku-sa-n --exit info

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Run `prettier`
        run: npx --yes prettier --check .
